"""empty message

Revision ID: 1b769301e42d
Revises: e7e3607ae32e
Create Date: 2016-08-28 21:06:23.884071

"""

# revision identifiers, used by Alembic.
revision = '1b769301e42d'
down_revision = 'e7e3607ae32e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('cover', sa.String(length=1024), nullable=True))
    op.add_column('posts', sa.Column('intro', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'intro')
    op.drop_column('posts', 'cover')
    ### end Alembic commands ###
