"""empty message

Revision ID: 5a3301a14a12
Revises: ed7b462aa260
Create Date: 2016-08-11 22:33:12.437458

"""

# revision identifiers, used by Alembic.
revision = '5a3301a14a12'
down_revision = 'ed7b462aa260'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###
