"""empty message

Revision ID: f18bbea9896c
Revises: 70ea65f4737b
Create Date: 2016-08-13 00:31:23.076978

"""

# revision identifiers, used by Alembic.
revision = 'f18bbea9896c'
down_revision = '70ea65f4737b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
